// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: payment_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentService_GetPaymentInfo_FullMethodName       = "/payment.v1.PaymentService/GetPaymentInfo"
	PaymentService_SubmitPaymentReceipt_FullMethodName = "/payment.v1.PaymentService/SubmitPaymentReceipt"
	PaymentService_GetReceipt_FullMethodName           = "/payment.v1.PaymentService/GetReceipt"
	PaymentService_VerifyReceipt_FullMethodName        = "/payment.v1.PaymentService/VerifyReceipt"
	PaymentService_GetReceiptFile_FullMethodName       = "/payment.v1.PaymentService/GetReceiptFile"
)

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentServiceClient interface {
	GetPaymentInfo(ctx context.Context, in *GetPaymentInfoRequest, opts ...grpc.CallOption) (*PaymentInfo, error)
	SubmitPaymentReceipt(ctx context.Context, in *SubmitPaymentReceiptRequest, opts ...grpc.CallOption) (*Receipt, error)
	GetReceipt(ctx context.Context, in *GetReceiptRequest, opts ...grpc.CallOption) (*Receipt, error)
	VerifyReceipt(ctx context.Context, in *VerifyReceiptRequest, opts ...grpc.CallOption) (*Receipt, error)
	GetReceiptFile(ctx context.Context, in *GetReceiptFileRequest, opts ...grpc.CallOption) (*ReceiptFileURL, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) GetPaymentInfo(ctx context.Context, in *GetPaymentInfoRequest, opts ...grpc.CallOption) (*PaymentInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PaymentInfo)
	err := c.cc.Invoke(ctx, PaymentService_GetPaymentInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) SubmitPaymentReceipt(ctx context.Context, in *SubmitPaymentReceiptRequest, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, PaymentService_SubmitPaymentReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetReceipt(ctx context.Context, in *GetReceiptRequest, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, PaymentService_GetReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) VerifyReceipt(ctx context.Context, in *VerifyReceiptRequest, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, PaymentService_VerifyReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetReceiptFile(ctx context.Context, in *GetReceiptFileRequest, opts ...grpc.CallOption) (*ReceiptFileURL, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReceiptFileURL)
	err := c.cc.Invoke(ctx, PaymentService_GetReceiptFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility.
type PaymentServiceServer interface {
	GetPaymentInfo(context.Context, *GetPaymentInfoRequest) (*PaymentInfo, error)
	SubmitPaymentReceipt(context.Context, *SubmitPaymentReceiptRequest) (*Receipt, error)
	GetReceipt(context.Context, *GetReceiptRequest) (*Receipt, error)
	VerifyReceipt(context.Context, *VerifyReceiptRequest) (*Receipt, error)
	GetReceiptFile(context.Context, *GetReceiptFileRequest) (*ReceiptFileURL, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) GetPaymentInfo(context.Context, *GetPaymentInfoRequest) (*PaymentInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaymentInfo not implemented")
}
func (UnimplementedPaymentServiceServer) SubmitPaymentReceipt(context.Context, *SubmitPaymentReceiptRequest) (*Receipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitPaymentReceipt not implemented")
}
func (UnimplementedPaymentServiceServer) GetReceipt(context.Context, *GetReceiptRequest) (*Receipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReceipt not implemented")
}
func (UnimplementedPaymentServiceServer) VerifyReceipt(context.Context, *VerifyReceiptRequest) (*Receipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyReceipt not implemented")
}
func (UnimplementedPaymentServiceServer) GetReceiptFile(context.Context, *GetReceiptFileRequest) (*ReceiptFileURL, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReceiptFile not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}
func (UnimplementedPaymentServiceServer) testEmbeddedByValue()                        {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	// If the following call pancis, it indicates UnimplementedPaymentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_GetPaymentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetPaymentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetPaymentInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetPaymentInfo(ctx, req.(*GetPaymentInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_SubmitPaymentReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitPaymentReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).SubmitPaymentReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_SubmitPaymentReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).SubmitPaymentReceipt(ctx, req.(*SubmitPaymentReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetReceipt(ctx, req.(*GetReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_VerifyReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).VerifyReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_VerifyReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).VerifyReceipt(ctx, req.(*VerifyReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetReceiptFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReceiptFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetReceiptFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetReceiptFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetReceiptFile(ctx, req.(*GetReceiptFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.v1.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPaymentInfo",
			Handler:    _PaymentService_GetPaymentInfo_Handler,
		},
		{
			MethodName: "SubmitPaymentReceipt",
			Handler:    _PaymentService_SubmitPaymentReceipt_Handler,
		},
		{
			MethodName: "GetReceipt",
			Handler:    _PaymentService_GetReceipt_Handler,
		},
		{
			MethodName: "VerifyReceipt",
			Handler:    _PaymentService_VerifyReceipt_Handler,
		},
		{
			MethodName: "GetReceiptFile",
			Handler:    _PaymentService_GetReceiptFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment_service.proto",
}
