image: golang:1.24-alpine

stages:
  - test
  - build

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  COMPOSE_VERSION: "v2.23.0"
  CGO_ENABLED: "1"
  GOOS: "linux"

before_script:
  - apk add --no-cache docker-cli docker-cli-compose build-base
  - docker --version
  - docker compose version

test_payment_service:
  stage: test
  script:
    - cd payment_service/internal/service
    - go test -race -coverprofile=coverage.out -covermode=atomic ./...
    - |
      TOTAL_COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
      echo "Total test coverage: $TOTAL_COVERAGE%"
      if (( $(echo "$TOTAL_COVERAGE < $COVERAGE_THRESHOLD" | bc -l) )); then
        echo "Coverage is below $COVERAGE_THRESHOLD% threshold"
        exit 1
      fi
  artifacts:
    paths:
      - payment_service/internal/service/coverage.out
    reports:
      cobertura: payment_service/internal/service/coverage.out

build_services:
  stage: build
  needs: ["test_payment_service"]
  script:
    - docker compose build
  artifacts:
    paths:
      - ./*/Dockerfile
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
