// Code generated by MockGen. DO NOT EDIT.
// Source: internal/database/repo/repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/database/repo/repo.go -destination=pkg/mocks/schedule_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	repo "schedule_service/internal/database/repo"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CancelLessonAndFreeSlot mocks base method.
func (m *MockRepository) CancelLessonAndFreeSlot(ctx context.Context, lesson repo.Lesson, slotID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelLessonAndFreeSlot", ctx, lesson, slotID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelLessonAndFreeSlot indicates an expected call of CancelLessonAndFreeSlot.
func (mr *MockRepositoryMockRecorder) CancelLessonAndFreeSlot(ctx, lesson, slotID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelLessonAndFreeSlot", reflect.TypeOf((*MockRepository)(nil).CancelLessonAndFreeSlot), ctx, lesson, slotID)
}

// CreateLessonAndBookSlot mocks base method.
func (m *MockRepository) CreateLessonAndBookSlot(ctx context.Context, lesson repo.Lesson, slotID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLessonAndBookSlot", ctx, lesson, slotID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLessonAndBookSlot indicates an expected call of CreateLessonAndBookSlot.
func (mr *MockRepositoryMockRecorder) CreateLessonAndBookSlot(ctx, lesson, slotID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLessonAndBookSlot", reflect.TypeOf((*MockRepository)(nil).CreateLessonAndBookSlot), ctx, lesson, slotID)
}

// CreateSlot mocks base method.
func (m *MockRepository) CreateSlot(ctx context.Context, slot repo.Slot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSlot", ctx, slot)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSlot indicates an expected call of CreateSlot.
func (mr *MockRepositoryMockRecorder) CreateSlot(ctx, slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSlot", reflect.TypeOf((*MockRepository)(nil).CreateSlot), ctx, slot)
}

// DeleteSlot mocks base method.
func (m *MockRepository) DeleteSlot(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSlot", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSlot indicates an expected call of DeleteSlot.
func (mr *MockRepositoryMockRecorder) DeleteSlot(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSlot", reflect.TypeOf((*MockRepository)(nil).DeleteSlot), ctx, id)
}

// GetLesson mocks base method.
func (m *MockRepository) GetLesson(ctx context.Context, id string) (*repo.Lesson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLesson", ctx, id)
	ret0, _ := ret[0].(*repo.Lesson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLesson indicates an expected call of GetLesson.
func (mr *MockRepositoryMockRecorder) GetLesson(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLesson", reflect.TypeOf((*MockRepository)(nil).GetLesson), ctx, id)
}

// GetSlot mocks base method.
func (m *MockRepository) GetSlot(ctx context.Context, id string) (*repo.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlot", ctx, id)
	ret0, _ := ret[0].(*repo.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlot indicates an expected call of GetSlot.
func (mr *MockRepositoryMockRecorder) GetSlot(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlot", reflect.TypeOf((*MockRepository)(nil).GetSlot), ctx, id)
}

// ListCompletedUnpaidLessons mocks base method.
func (m *MockRepository) ListCompletedUnpaidLessons(ctx context.Context, after *time.Time) ([]repo.Lesson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCompletedUnpaidLessons", ctx, after)
	ret0, _ := ret[0].([]repo.Lesson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCompletedUnpaidLessons indicates an expected call of ListCompletedUnpaidLessons.
func (mr *MockRepositoryMockRecorder) ListCompletedUnpaidLessons(ctx, after any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCompletedUnpaidLessons", reflect.TypeOf((*MockRepository)(nil).ListCompletedUnpaidLessons), ctx, after)
}

// ListLessonsByPair mocks base method.
func (m *MockRepository) ListLessonsByPair(ctx context.Context, tutorID, studentID string, statusFilter []string) ([]repo.Lesson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLessonsByPair", ctx, tutorID, studentID, statusFilter)
	ret0, _ := ret[0].([]repo.Lesson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLessonsByPair indicates an expected call of ListLessonsByPair.
func (mr *MockRepositoryMockRecorder) ListLessonsByPair(ctx, tutorID, studentID, statusFilter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLessonsByPair", reflect.TypeOf((*MockRepository)(nil).ListLessonsByPair), ctx, tutorID, studentID, statusFilter)
}

// ListLessonsByStudent mocks base method.
func (m *MockRepository) ListLessonsByStudent(ctx context.Context, studentID string, statusFilter []string) ([]repo.Lesson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLessonsByStudent", ctx, studentID, statusFilter)
	ret0, _ := ret[0].([]repo.Lesson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLessonsByStudent indicates an expected call of ListLessonsByStudent.
func (mr *MockRepositoryMockRecorder) ListLessonsByStudent(ctx, studentID, statusFilter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLessonsByStudent", reflect.TypeOf((*MockRepository)(nil).ListLessonsByStudent), ctx, studentID, statusFilter)
}

// ListLessonsByTutor mocks base method.
func (m *MockRepository) ListLessonsByTutor(ctx context.Context, tutorID string, statusFilter []string) ([]repo.Lesson, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLessonsByTutor", ctx, tutorID, statusFilter)
	ret0, _ := ret[0].([]repo.Lesson)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLessonsByTutor indicates an expected call of ListLessonsByTutor.
func (mr *MockRepositoryMockRecorder) ListLessonsByTutor(ctx, tutorID, statusFilter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLessonsByTutor", reflect.TypeOf((*MockRepository)(nil).ListLessonsByTutor), ctx, tutorID, statusFilter)
}

// ListSlotsByTutor mocks base method.
func (m *MockRepository) ListSlotsByTutor(ctx context.Context, tutorID string, onlyAvailable bool) ([]repo.Slot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSlotsByTutor", ctx, tutorID, onlyAvailable)
	ret0, _ := ret[0].([]repo.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSlotsByTutor indicates an expected call of ListSlotsByTutor.
func (mr *MockRepositoryMockRecorder) ListSlotsByTutor(ctx, tutorID, onlyAvailable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSlotsByTutor", reflect.TypeOf((*MockRepository)(nil).ListSlotsByTutor), ctx, tutorID, onlyAvailable)
}

// MarkAsPaid mocks base method.
func (m *MockRepository) MarkAsPaid(ctx context.Context, lessonID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsPaid", ctx, lessonID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsPaid indicates an expected call of MarkAsPaid.
func (mr *MockRepositoryMockRecorder) MarkAsPaid(ctx, lessonID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsPaid", reflect.TypeOf((*MockRepository)(nil).MarkAsPaid), ctx, lessonID)
}

// UpdateCompletedLessons mocks base method.
func (m *MockRepository) UpdateCompletedLessons(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCompletedLessons", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCompletedLessons indicates an expected call of UpdateCompletedLessons.
func (mr *MockRepositoryMockRecorder) UpdateCompletedLessons(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCompletedLessons", reflect.TypeOf((*MockRepository)(nil).UpdateCompletedLessons), ctx)
}

// UpdateLesson mocks base method.
func (m *MockRepository) UpdateLesson(ctx context.Context, lesson repo.Lesson) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLesson", ctx, lesson)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLesson indicates an expected call of UpdateLesson.
func (mr *MockRepositoryMockRecorder) UpdateLesson(ctx, lesson any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLesson", reflect.TypeOf((*MockRepository)(nil).UpdateLesson), ctx, lesson)
}

// UpdateSlot mocks base method.
func (m *MockRepository) UpdateSlot(ctx context.Context, slot repo.Slot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSlot", ctx, slot)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSlot indicates an expected call of UpdateSlot.
func (mr *MockRepositoryMockRecorder) UpdateSlot(ctx, slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSlot", reflect.TypeOf((*MockRepository)(nil).UpdateSlot), ctx, slot)
}
