// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/service/utils.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/service/utils.go -destination=pkg/mocks/user_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	api "userservice/pkg/api"

	gomock "go.uber.org/mock/gomock"
)

// MockIUserClient is a mock of IUserClient interface.
type MockIUserClient struct {
	ctrl     *gomock.Controller
	recorder *MockIUserClientMockRecorder
	isgomock struct{}
}

// MockIUserClientMockRecorder is the mock recorder for MockIUserClient.
type MockIUserClientMockRecorder struct {
	mock *MockIUserClient
}

// NewMockIUserClient creates a new mock instance.
func NewMockIUserClient(ctrl *gomock.Controller) *MockIUserClient {
	mock := &MockIUserClient{ctrl: ctrl}
	mock.recorder = &MockIUserClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserClient) EXPECT() *MockIUserClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockIUserClient) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockIUserClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIUserClient)(nil).Close))
}

// GetTutorStudent mocks base method.
func (m *MockIUserClient) GetTutorStudent(ctx context.Context, tutorID, studentID string) (*api.TutorStudent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTutorStudent", ctx, tutorID, studentID)
	ret0, _ := ret[0].(*api.TutorStudent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTutorStudent indicates an expected call of GetTutorStudent.
func (mr *MockIUserClientMockRecorder) GetTutorStudent(ctx, tutorID, studentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTutorStudent", reflect.TypeOf((*MockIUserClient)(nil).GetTutorStudent), ctx, tutorID, studentID)
}
