// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: user_service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterViaTelegramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TelegramId    int64                  `protobuf:"varint,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Username      *string                `protobuf:"bytes,3,opt,name=username,proto3,oneof" json:"username,omitempty"`
	FirstName     *string                `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	Timezone      *string                `protobuf:"bytes,6,opt,name=timezone,proto3,oneof" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterViaTelegramRequest) Reset() {
	*x = RegisterViaTelegramRequest{}
	mi := &file_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterViaTelegramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterViaTelegramRequest) ProtoMessage() {}

func (x *RegisterViaTelegramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterViaTelegramRequest.ProtoReflect.Descriptor instead.
func (*RegisterViaTelegramRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterViaTelegramRequest) GetTelegramId() int64 {
	if x != nil {
		return x.TelegramId
	}
	return 0
}

func (x *RegisterViaTelegramRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RegisterViaTelegramRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *RegisterViaTelegramRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *RegisterViaTelegramRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *RegisterViaTelegramRequest) GetTimezone() string {
	if x != nil && x.Timezone != nil {
		return *x.Timezone
	}
	return ""
}

type AuthorizeByAuthHeaderRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AuthorizationHeader string                 `protobuf:"bytes,1,opt,name=authorization_header,json=authorizationHeader,proto3" json:"authorization_header,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AuthorizeByAuthHeaderRequest) Reset() {
	*x = AuthorizeByAuthHeaderRequest{}
	mi := &file_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeByAuthHeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeByAuthHeaderRequest) ProtoMessage() {}

func (x *AuthorizeByAuthHeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeByAuthHeaderRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeByAuthHeaderRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizeByAuthHeaderRequest) GetAuthorizationHeader() string {
	if x != nil {
		return x.AuthorizationHeader
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     *string                `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	Timezone      *string                `protobuf:"bytes,4,opt,name=timezone,proto3,oneof" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UpdateUserRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *UpdateUserRequest) GetTimezone() string {
	if x != nil && x.Timezone != nil {
		return *x.Timezone
	}
	return ""
}

type GetTutorProfileByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTutorProfileByUserIdRequest) Reset() {
	*x = GetTutorProfileByUserIdRequest{}
	mi := &file_user_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTutorProfileByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTutorProfileByUserIdRequest) ProtoMessage() {}

func (x *GetTutorProfileByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTutorProfileByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetTutorProfileByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetTutorProfileByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateTutorProfileRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PaymentInfo          *string                `protobuf:"bytes,2,opt,name=payment_info,json=paymentInfo,proto3,oneof" json:"payment_info,omitempty"`
	LessonPriceRub       *int32                 `protobuf:"varint,3,opt,name=lesson_price_rub,json=lessonPriceRub,proto3,oneof" json:"lesson_price_rub,omitempty"`
	LessonConnectionLink *string                `protobuf:"bytes,4,opt,name=lesson_connection_link,json=lessonConnectionLink,proto3,oneof" json:"lesson_connection_link,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateTutorProfileRequest) Reset() {
	*x = UpdateTutorProfileRequest{}
	mi := &file_user_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTutorProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTutorProfileRequest) ProtoMessage() {}

func (x *UpdateTutorProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTutorProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateTutorProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTutorProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateTutorProfileRequest) GetPaymentInfo() string {
	if x != nil && x.PaymentInfo != nil {
		return *x.PaymentInfo
	}
	return ""
}

func (x *UpdateTutorProfileRequest) GetLessonPriceRub() int32 {
	if x != nil && x.LessonPriceRub != nil {
		return *x.LessonPriceRub
	}
	return 0
}

func (x *UpdateTutorProfileRequest) GetLessonConnectionLink() string {
	if x != nil && x.LessonConnectionLink != nil {
		return *x.LessonConnectionLink
	}
	return ""
}

type GetTutorStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TutorId       string                 `protobuf:"bytes,1,opt,name=tutor_id,json=tutorId,proto3" json:"tutor_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTutorStudentRequest) Reset() {
	*x = GetTutorStudentRequest{}
	mi := &file_user_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTutorStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTutorStudentRequest) ProtoMessage() {}

func (x *GetTutorStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTutorStudentRequest.ProtoReflect.Descriptor instead.
func (*GetTutorStudentRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetTutorStudentRequest) GetTutorId() string {
	if x != nil {
		return x.TutorId
	}
	return ""
}

func (x *GetTutorStudentRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type CreateTutorStudentRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TutorId              string                 `protobuf:"bytes,1,opt,name=tutor_id,json=tutorId,proto3" json:"tutor_id,omitempty"`
	StudentId            string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	LessonPriceRub       *int32                 `protobuf:"varint,3,opt,name=lesson_price_rub,json=lessonPriceRub,proto3,oneof" json:"lesson_price_rub,omitempty"`
	LessonConnectionLink *string                `protobuf:"bytes,4,opt,name=lesson_connection_link,json=lessonConnectionLink,proto3,oneof" json:"lesson_connection_link,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateTutorStudentRequest) Reset() {
	*x = CreateTutorStudentRequest{}
	mi := &file_user_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTutorStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTutorStudentRequest) ProtoMessage() {}

func (x *CreateTutorStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTutorStudentRequest.ProtoReflect.Descriptor instead.
func (*CreateTutorStudentRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTutorStudentRequest) GetTutorId() string {
	if x != nil {
		return x.TutorId
	}
	return ""
}

func (x *CreateTutorStudentRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *CreateTutorStudentRequest) GetLessonPriceRub() int32 {
	if x != nil && x.LessonPriceRub != nil {
		return *x.LessonPriceRub
	}
	return 0
}

func (x *CreateTutorStudentRequest) GetLessonConnectionLink() string {
	if x != nil && x.LessonConnectionLink != nil {
		return *x.LessonConnectionLink
	}
	return ""
}

type UpdateTutorStudentRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TutorId              string                 `protobuf:"bytes,1,opt,name=tutor_id,json=tutorId,proto3" json:"tutor_id,omitempty"`
	StudentId            string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	LessonPriceRub       *int32                 `protobuf:"varint,3,opt,name=lesson_price_rub,json=lessonPriceRub,proto3,oneof" json:"lesson_price_rub,omitempty"`
	LessonConnectionLink *string                `protobuf:"bytes,4,opt,name=lesson_connection_link,json=lessonConnectionLink,proto3,oneof" json:"lesson_connection_link,omitempty"`
	Status               *string                `protobuf:"bytes,5,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateTutorStudentRequest) Reset() {
	*x = UpdateTutorStudentRequest{}
	mi := &file_user_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTutorStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTutorStudentRequest) ProtoMessage() {}

func (x *UpdateTutorStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTutorStudentRequest.ProtoReflect.Descriptor instead.
func (*UpdateTutorStudentRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTutorStudentRequest) GetTutorId() string {
	if x != nil {
		return x.TutorId
	}
	return ""
}

func (x *UpdateTutorStudentRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *UpdateTutorStudentRequest) GetLessonPriceRub() int32 {
	if x != nil && x.LessonPriceRub != nil {
		return *x.LessonPriceRub
	}
	return 0
}

func (x *UpdateTutorStudentRequest) GetLessonConnectionLink() string {
	if x != nil && x.LessonConnectionLink != nil {
		return *x.LessonConnectionLink
	}
	return ""
}

func (x *UpdateTutorStudentRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type DeleteTutorStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TutorId       string                 `protobuf:"bytes,1,opt,name=tutor_id,json=tutorId,proto3" json:"tutor_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTutorStudentRequest) Reset() {
	*x = DeleteTutorStudentRequest{}
	mi := &file_user_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTutorStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTutorStudentRequest) ProtoMessage() {}

func (x *DeleteTutorStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTutorStudentRequest.ProtoReflect.Descriptor instead.
func (*DeleteTutorStudentRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTutorStudentRequest) GetTutorId() string {
	if x != nil {
		return x.TutorId
	}
	return ""
}

func (x *DeleteTutorStudentRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type ListTutorStudentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TutorId       string                 `protobuf:"bytes,1,opt,name=tutor_id,json=tutorId,proto3" json:"tutor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTutorStudentsRequest) Reset() {
	*x = ListTutorStudentsRequest{}
	mi := &file_user_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTutorStudentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTutorStudentsRequest) ProtoMessage() {}

func (x *ListTutorStudentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTutorStudentsRequest.ProtoReflect.Descriptor instead.
func (*ListTutorStudentsRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListTutorStudentsRequest) GetTutorId() string {
	if x != nil {
		return x.TutorId
	}
	return ""
}

type ListTutorStudentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Students      []*TutorStudent        `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTutorStudentsResponse) Reset() {
	*x = ListTutorStudentsResponse{}
	mi := &file_user_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTutorStudentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTutorStudentsResponse) ProtoMessage() {}

func (x *ListTutorStudentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTutorStudentsResponse.ProtoReflect.Descriptor instead.
func (*ListTutorStudentsResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListTutorStudentsResponse) GetStudents() []*TutorStudent {
	if x != nil {
		return x.Students
	}
	return nil
}

type ListTutorsForStudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTutorsForStudentRequest) Reset() {
	*x = ListTutorsForStudentRequest{}
	mi := &file_user_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTutorsForStudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTutorsForStudentRequest) ProtoMessage() {}

func (x *ListTutorsForStudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTutorsForStudentRequest.ProtoReflect.Descriptor instead.
func (*ListTutorsForStudentRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListTutorsForStudentRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type ListTutorsForStudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tutors        []*TutorStudent        `protobuf:"bytes,1,rep,name=tutors,proto3" json:"tutors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTutorsForStudentResponse) Reset() {
	*x = ListTutorsForStudentResponse{}
	mi := &file_user_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTutorsForStudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTutorsForStudentResponse) ProtoMessage() {}

func (x *ListTutorsForStudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTutorsForStudentResponse.ProtoReflect.Descriptor instead.
func (*ListTutorsForStudentResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListTutorsForStudentResponse) GetTutors() []*TutorStudent {
	if x != nil {
		return x.Tutors
	}
	return nil
}

type ResolveTutorStudentContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TutorId       string                 `protobuf:"bytes,1,opt,name=tutor_id,json=tutorId,proto3" json:"tutor_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveTutorStudentContextRequest) Reset() {
	*x = ResolveTutorStudentContextRequest{}
	mi := &file_user_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveTutorStudentContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveTutorStudentContextRequest) ProtoMessage() {}

func (x *ResolveTutorStudentContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveTutorStudentContextRequest.ProtoReflect.Descriptor instead.
func (*ResolveTutorStudentContextRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{14}
}

func (x *ResolveTutorStudentContextRequest) GetTutorId() string {
	if x != nil {
		return x.TutorId
	}
	return ""
}

func (x *ResolveTutorStudentContextRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type ResolvedTutorStudentContext struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RelationshipStatus   string                 `protobuf:"bytes,2,opt,name=relationship_status,json=relationshipStatus,proto3" json:"relationship_status,omitempty"` // invited / active / blocked / removed
	LessonPriceRub       *int32                 `protobuf:"varint,3,opt,name=lesson_price_rub,json=lessonPriceRub,proto3,oneof" json:"lesson_price_rub,omitempty"`
	LessonConnectionLink *string                `protobuf:"bytes,4,opt,name=lesson_connection_link,json=lessonConnectionLink,proto3,oneof" json:"lesson_connection_link,omitempty"`
	PaymentInfo          *string                `protobuf:"bytes,5,opt,name=payment_info,json=paymentInfo,proto3,oneof" json:"payment_info,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ResolvedTutorStudentContext) Reset() {
	*x = ResolvedTutorStudentContext{}
	mi := &file_user_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedTutorStudentContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedTutorStudentContext) ProtoMessage() {}

func (x *ResolvedTutorStudentContext) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedTutorStudentContext.ProtoReflect.Descriptor instead.
func (*ResolvedTutorStudentContext) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{15}
}

func (x *ResolvedTutorStudentContext) GetRelationshipStatus() string {
	if x != nil {
		return x.RelationshipStatus
	}
	return ""
}

func (x *ResolvedTutorStudentContext) GetLessonPriceRub() int32 {
	if x != nil && x.LessonPriceRub != nil {
		return *x.LessonPriceRub
	}
	return 0
}

func (x *ResolvedTutorStudentContext) GetLessonConnectionLink() string {
	if x != nil && x.LessonConnectionLink != nil {
		return *x.LessonConnectionLink
	}
	return ""
}

func (x *ResolvedTutorStudentContext) GetPaymentInfo() string {
	if x != nil && x.PaymentInfo != nil {
		return *x.PaymentInfo
	}
	return ""
}

type AcceptInvitationFromTutorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TutorId       string                 `protobuf:"bytes,1,opt,name=tutor_id,json=tutorId,proto3" json:"tutor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInvitationFromTutorRequest) Reset() {
	*x = AcceptInvitationFromTutorRequest{}
	mi := &file_user_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInvitationFromTutorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInvitationFromTutorRequest) ProtoMessage() {}

func (x *AcceptInvitationFromTutorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInvitationFromTutorRequest.ProtoReflect.Descriptor instead.
func (*AcceptInvitationFromTutorRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{16}
}

func (x *AcceptInvitationFromTutorRequest) GetTutorId() string {
	if x != nil {
		return x.TutorId
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_user_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{17}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"` // tutor / student
	AuthProvider  string                 `protobuf:"bytes,3,opt,name=auth_provider,json=authProvider,proto3" json:"auth_provider,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // active / blocked / deleted
	FirstName     *string                `protobuf:"bytes,5,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,6,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	Timezone      *string                `protobuf:"bytes,7,opt,name=timezone,proto3,oneof" json:"timezone,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	EditedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=edited_at,json=editedAt,proto3" json:"edited_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{18}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetAuthProvider() string {
	if x != nil {
		return x.AuthProvider
	}
	return ""
}

func (x *User) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *User) GetTimezone() string {
	if x != nil && x.Timezone != nil {
		return *x.Timezone
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetEditedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EditedAt
	}
	return nil
}

type UserPublic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	FirstName     *string                `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPublic) Reset() {
	*x = UserPublic{}
	mi := &file_user_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPublic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPublic) ProtoMessage() {}

func (x *UserPublic) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPublic.ProtoReflect.Descriptor instead.
func (*UserPublic) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{19}
}

func (x *UserPublic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserPublic) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserPublic) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UserPublic) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

type TutorProfile struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PaymentInfo          *string                `protobuf:"bytes,3,opt,name=payment_info,json=paymentInfo,proto3,oneof" json:"payment_info,omitempty"`
	LessonPriceRub       *int32                 `protobuf:"varint,4,opt,name=lesson_price_rub,json=lessonPriceRub,proto3,oneof" json:"lesson_price_rub,omitempty"`
	LessonConnectionLink *string                `protobuf:"bytes,5,opt,name=lesson_connection_link,json=lessonConnectionLink,proto3,oneof" json:"lesson_connection_link,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	EditedAt             *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=edited_at,json=editedAt,proto3" json:"edited_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TutorProfile) Reset() {
	*x = TutorProfile{}
	mi := &file_user_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TutorProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TutorProfile) ProtoMessage() {}

func (x *TutorProfile) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TutorProfile.ProtoReflect.Descriptor instead.
func (*TutorProfile) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{20}
}

func (x *TutorProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TutorProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TutorProfile) GetPaymentInfo() string {
	if x != nil && x.PaymentInfo != nil {
		return *x.PaymentInfo
	}
	return ""
}

func (x *TutorProfile) GetLessonPriceRub() int32 {
	if x != nil && x.LessonPriceRub != nil {
		return *x.LessonPriceRub
	}
	return 0
}

func (x *TutorProfile) GetLessonConnectionLink() string {
	if x != nil && x.LessonConnectionLink != nil {
		return *x.LessonConnectionLink
	}
	return ""
}

func (x *TutorProfile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TutorProfile) GetEditedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EditedAt
	}
	return nil
}

type TutorStudent struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TutorId              string                 `protobuf:"bytes,2,opt,name=tutor_id,json=tutorId,proto3" json:"tutor_id,omitempty"`
	StudentId            string                 `protobuf:"bytes,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	LessonPriceRub       *int32                 `protobuf:"varint,4,opt,name=lesson_price_rub,json=lessonPriceRub,proto3,oneof" json:"lesson_price_rub,omitempty"`
	LessonConnectionLink *string                `protobuf:"bytes,5,opt,name=lesson_connection_link,json=lessonConnectionLink,proto3,oneof" json:"lesson_connection_link,omitempty"`
	Status               string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // invited / active / blocked / removed
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	EditedAt             *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=edited_at,json=editedAt,proto3" json:"edited_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TutorStudent) Reset() {
	*x = TutorStudent{}
	mi := &file_user_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TutorStudent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TutorStudent) ProtoMessage() {}

func (x *TutorStudent) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TutorStudent.ProtoReflect.Descriptor instead.
func (*TutorStudent) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{21}
}

func (x *TutorStudent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TutorStudent) GetTutorId() string {
	if x != nil {
		return x.TutorId
	}
	return ""
}

func (x *TutorStudent) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *TutorStudent) GetLessonPriceRub() int32 {
	if x != nil && x.LessonPriceRub != nil {
		return *x.LessonPriceRub
	}
	return 0
}

func (x *TutorStudent) GetLessonConnectionLink() string {
	if x != nil && x.LessonConnectionLink != nil {
		return *x.LessonConnectionLink
	}
	return ""
}

func (x *TutorStudent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TutorStudent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TutorStudent) GetEditedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EditedAt
	}
	return nil
}

var File_user_service_proto protoreflect.FileDescriptor

const file_user_service_proto_rawDesc = "" +
	"\n" +
	"\x12user_service.proto\x12\auser.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x02\n" +
	"\x1aRegisterViaTelegramRequest\x12\x1f\n" +
	"\vtelegram_id\x18\x01 \x01(\x03R\n" +
	"telegramId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1f\n" +
	"\busername\x18\x03 \x01(\tH\x00R\busername\x88\x01\x01\x12\"\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tH\x01R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x05 \x01(\tH\x02R\blastName\x88\x01\x01\x12\x1f\n" +
	"\btimezone\x18\x06 \x01(\tH\x03R\btimezone\x88\x01\x01B\v\n" +
	"\t_usernameB\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\v\n" +
	"\t_timezone\"Q\n" +
	"\x1cAuthorizeByAuthHeaderRequest\x121\n" +
	"\x14authorization_header\x18\x01 \x01(\tR\x13authorizationHeader\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb4\x01\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tH\x00R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x03 \x01(\tH\x01R\blastName\x88\x01\x01\x12\x1f\n" +
	"\btimezone\x18\x04 \x01(\tH\x02R\btimezone\x88\x01\x01B\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\v\n" +
	"\t_timezone\"9\n" +
	"\x1eGetTutorProfileByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x87\x02\n" +
	"\x19UpdateTutorProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\fpayment_info\x18\x02 \x01(\tH\x00R\vpaymentInfo\x88\x01\x01\x12-\n" +
	"\x10lesson_price_rub\x18\x03 \x01(\x05H\x01R\x0elessonPriceRub\x88\x01\x01\x129\n" +
	"\x16lesson_connection_link\x18\x04 \x01(\tH\x02R\x14lessonConnectionLink\x88\x01\x01B\x0f\n" +
	"\r_payment_infoB\x13\n" +
	"\x11_lesson_price_rubB\x19\n" +
	"\x17_lesson_connection_link\"R\n" +
	"\x16GetTutorStudentRequest\x12\x19\n" +
	"\btutor_id\x18\x01 \x01(\tR\atutorId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\"\xef\x01\n" +
	"\x19CreateTutorStudentRequest\x12\x19\n" +
	"\btutor_id\x18\x01 \x01(\tR\atutorId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12-\n" +
	"\x10lesson_price_rub\x18\x03 \x01(\x05H\x00R\x0elessonPriceRub\x88\x01\x01\x129\n" +
	"\x16lesson_connection_link\x18\x04 \x01(\tH\x01R\x14lessonConnectionLink\x88\x01\x01B\x13\n" +
	"\x11_lesson_price_rubB\x19\n" +
	"\x17_lesson_connection_link\"\x97\x02\n" +
	"\x19UpdateTutorStudentRequest\x12\x19\n" +
	"\btutor_id\x18\x01 \x01(\tR\atutorId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12-\n" +
	"\x10lesson_price_rub\x18\x03 \x01(\x05H\x00R\x0elessonPriceRub\x88\x01\x01\x129\n" +
	"\x16lesson_connection_link\x18\x04 \x01(\tH\x01R\x14lessonConnectionLink\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x05 \x01(\tH\x02R\x06status\x88\x01\x01B\x13\n" +
	"\x11_lesson_price_rubB\x19\n" +
	"\x17_lesson_connection_linkB\t\n" +
	"\a_status\"U\n" +
	"\x19DeleteTutorStudentRequest\x12\x19\n" +
	"\btutor_id\x18\x01 \x01(\tR\atutorId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\"5\n" +
	"\x18ListTutorStudentsRequest\x12\x19\n" +
	"\btutor_id\x18\x01 \x01(\tR\atutorId\"N\n" +
	"\x19ListTutorStudentsResponse\x121\n" +
	"\bstudents\x18\x01 \x03(\v2\x15.user.v1.TutorStudentR\bstudents\"<\n" +
	"\x1bListTutorsForStudentRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"M\n" +
	"\x1cListTutorsForStudentResponse\x12-\n" +
	"\x06tutors\x18\x01 \x03(\v2\x15.user.v1.TutorStudentR\x06tutors\"]\n" +
	"!ResolveTutorStudentContextRequest\x12\x19\n" +
	"\btutor_id\x18\x01 \x01(\tR\atutorId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\"\xa1\x02\n" +
	"\x1bResolvedTutorStudentContext\x12/\n" +
	"\x13relationship_status\x18\x02 \x01(\tR\x12relationshipStatus\x12-\n" +
	"\x10lesson_price_rub\x18\x03 \x01(\x05H\x00R\x0elessonPriceRub\x88\x01\x01\x129\n" +
	"\x16lesson_connection_link\x18\x04 \x01(\tH\x01R\x14lessonConnectionLink\x88\x01\x01\x12&\n" +
	"\fpayment_info\x18\x05 \x01(\tH\x02R\vpaymentInfo\x88\x01\x01B\x13\n" +
	"\x11_lesson_price_rubB\x19\n" +
	"\x17_lesson_connection_linkB\x0f\n" +
	"\r_payment_info\"=\n" +
	" AcceptInvitationFromTutorRequest\x12\x19\n" +
	"\btutor_id\x18\x01 \x01(\tR\atutorId\"\a\n" +
	"\x05Empty\"\xec\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12#\n" +
	"\rauth_provider\x18\x03 \x01(\tR\fauthProvider\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\"\n" +
	"\n" +
	"first_name\x18\x05 \x01(\tH\x00R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x06 \x01(\tH\x01R\blastName\x88\x01\x01\x12\x1f\n" +
	"\btimezone\x18\a \x01(\tH\x02R\btimezone\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\tedited_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\beditedAtB\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\v\n" +
	"\t_timezone\"\x93\x01\n" +
	"\n" +
	"UserPublic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\"\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tH\x00R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x04 \x01(\tH\x01R\blastName\x88\x01\x01B\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_name\"\xfe\x02\n" +
	"\fTutorProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12&\n" +
	"\fpayment_info\x18\x03 \x01(\tH\x00R\vpaymentInfo\x88\x01\x01\x12-\n" +
	"\x10lesson_price_rub\x18\x04 \x01(\x05H\x01R\x0elessonPriceRub\x88\x01\x01\x129\n" +
	"\x16lesson_connection_link\x18\x05 \x01(\tH\x02R\x14lessonConnectionLink\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\tedited_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\beditedAtB\x0f\n" +
	"\r_payment_infoB\x13\n" +
	"\x11_lesson_price_rubB\x19\n" +
	"\x17_lesson_connection_link\"\xfe\x02\n" +
	"\fTutorStudent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\btutor_id\x18\x02 \x01(\tR\atutorId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x03 \x01(\tR\tstudentId\x12-\n" +
	"\x10lesson_price_rub\x18\x04 \x01(\x05H\x00R\x0elessonPriceRub\x88\x01\x01\x129\n" +
	"\x16lesson_connection_link\x18\x05 \x01(\tH\x01R\x14lessonConnectionLink\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\tedited_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\beditedAtB\x13\n" +
	"\x11_lesson_price_rubB\x19\n" +
	"\x17_lesson_connection_link2\xad\t\n" +
	"\vUserService\x12I\n" +
	"\x13RegisterViaTelegram\x12#.user.v1.RegisterViaTelegramRequest\x1a\r.user.v1.User\x12M\n" +
	"\x15AuthorizeByAuthHeader\x12%.user.v1.AuthorizeByAuthHeaderRequest\x1a\r.user.v1.User\x12&\n" +
	"\x05GetMe\x12\x0e.user.v1.Empty\x1a\r.user.v1.User\x127\n" +
	"\aGetUser\x12\x17.user.v1.GetUserRequest\x1a\x13.user.v1.UserPublic\x127\n" +
	"\n" +
	"UpdateUser\x12\x1a.user.v1.UpdateUserRequest\x1a\r.user.v1.User\x12O\n" +
	"\x12UpdateTutorProfile\x12\".user.v1.UpdateTutorProfileRequest\x1a\x15.user.v1.TutorProfile\x12Y\n" +
	"\x17GetTutorProfileByUserId\x12'.user.v1.GetTutorProfileByUserIdRequest\x1a\x15.user.v1.TutorProfile\x12I\n" +
	"\x0fGetTutorStudent\x12\x1f.user.v1.GetTutorStudentRequest\x1a\x15.user.v1.TutorStudent\x12O\n" +
	"\x12CreateTutorStudent\x12\".user.v1.CreateTutorStudentRequest\x1a\x15.user.v1.TutorStudent\x12O\n" +
	"\x12UpdateTutorStudent\x12\".user.v1.UpdateTutorStudentRequest\x1a\x15.user.v1.TutorStudent\x12H\n" +
	"\x12DeleteTutorStudent\x12\".user.v1.DeleteTutorStudentRequest\x1a\x0e.user.v1.Empty\x12Z\n" +
	"\x11ListTutorStudents\x12!.user.v1.ListTutorStudentsRequest\x1a\".user.v1.ListTutorStudentsResponse\x12c\n" +
	"\x14ListTutorsForStudent\x12$.user.v1.ListTutorsForStudentRequest\x1a%.user.v1.ListTutorsForStudentResponse\x12n\n" +
	"\x1aResolveTutorStudentContext\x12*.user.v1.ResolveTutorStudentContextRequest\x1a$.user.v1.ResolvedTutorStudentContext\x12V\n" +
	"\x19AcceptInvitationFromTutor\x12).user.v1.AcceptInvitationFromTutorRequest\x1a\x0e.user.v1.EmptyB\tZ\apkg/apib\x06proto3"

var (
	file_user_service_proto_rawDescOnce sync.Once
	file_user_service_proto_rawDescData []byte
)

func file_user_service_proto_rawDescGZIP() []byte {
	file_user_service_proto_rawDescOnce.Do(func() {
		file_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_proto_rawDesc), len(file_user_service_proto_rawDesc)))
	})
	return file_user_service_proto_rawDescData
}

var file_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_user_service_proto_goTypes = []any{
	(*RegisterViaTelegramRequest)(nil),        // 0: user.v1.RegisterViaTelegramRequest
	(*AuthorizeByAuthHeaderRequest)(nil),      // 1: user.v1.AuthorizeByAuthHeaderRequest
	(*GetUserRequest)(nil),                    // 2: user.v1.GetUserRequest
	(*UpdateUserRequest)(nil),                 // 3: user.v1.UpdateUserRequest
	(*GetTutorProfileByUserIdRequest)(nil),    // 4: user.v1.GetTutorProfileByUserIdRequest
	(*UpdateTutorProfileRequest)(nil),         // 5: user.v1.UpdateTutorProfileRequest
	(*GetTutorStudentRequest)(nil),            // 6: user.v1.GetTutorStudentRequest
	(*CreateTutorStudentRequest)(nil),         // 7: user.v1.CreateTutorStudentRequest
	(*UpdateTutorStudentRequest)(nil),         // 8: user.v1.UpdateTutorStudentRequest
	(*DeleteTutorStudentRequest)(nil),         // 9: user.v1.DeleteTutorStudentRequest
	(*ListTutorStudentsRequest)(nil),          // 10: user.v1.ListTutorStudentsRequest
	(*ListTutorStudentsResponse)(nil),         // 11: user.v1.ListTutorStudentsResponse
	(*ListTutorsForStudentRequest)(nil),       // 12: user.v1.ListTutorsForStudentRequest
	(*ListTutorsForStudentResponse)(nil),      // 13: user.v1.ListTutorsForStudentResponse
	(*ResolveTutorStudentContextRequest)(nil), // 14: user.v1.ResolveTutorStudentContextRequest
	(*ResolvedTutorStudentContext)(nil),       // 15: user.v1.ResolvedTutorStudentContext
	(*AcceptInvitationFromTutorRequest)(nil),  // 16: user.v1.AcceptInvitationFromTutorRequest
	(*Empty)(nil),                             // 17: user.v1.Empty
	(*User)(nil),                              // 18: user.v1.User
	(*UserPublic)(nil),                        // 19: user.v1.UserPublic
	(*TutorProfile)(nil),                      // 20: user.v1.TutorProfile
	(*TutorStudent)(nil),                      // 21: user.v1.TutorStudent
	(*timestamppb.Timestamp)(nil),             // 22: google.protobuf.Timestamp
}
var file_user_service_proto_depIdxs = []int32{
	21, // 0: user.v1.ListTutorStudentsResponse.students:type_name -> user.v1.TutorStudent
	21, // 1: user.v1.ListTutorsForStudentResponse.tutors:type_name -> user.v1.TutorStudent
	22, // 2: user.v1.User.created_at:type_name -> google.protobuf.Timestamp
	22, // 3: user.v1.User.edited_at:type_name -> google.protobuf.Timestamp
	22, // 4: user.v1.TutorProfile.created_at:type_name -> google.protobuf.Timestamp
	22, // 5: user.v1.TutorProfile.edited_at:type_name -> google.protobuf.Timestamp
	22, // 6: user.v1.TutorStudent.created_at:type_name -> google.protobuf.Timestamp
	22, // 7: user.v1.TutorStudent.edited_at:type_name -> google.protobuf.Timestamp
	0,  // 8: user.v1.UserService.RegisterViaTelegram:input_type -> user.v1.RegisterViaTelegramRequest
	1,  // 9: user.v1.UserService.AuthorizeByAuthHeader:input_type -> user.v1.AuthorizeByAuthHeaderRequest
	17, // 10: user.v1.UserService.GetMe:input_type -> user.v1.Empty
	2,  // 11: user.v1.UserService.GetUser:input_type -> user.v1.GetUserRequest
	3,  // 12: user.v1.UserService.UpdateUser:input_type -> user.v1.UpdateUserRequest
	5,  // 13: user.v1.UserService.UpdateTutorProfile:input_type -> user.v1.UpdateTutorProfileRequest
	4,  // 14: user.v1.UserService.GetTutorProfileByUserId:input_type -> user.v1.GetTutorProfileByUserIdRequest
	6,  // 15: user.v1.UserService.GetTutorStudent:input_type -> user.v1.GetTutorStudentRequest
	7,  // 16: user.v1.UserService.CreateTutorStudent:input_type -> user.v1.CreateTutorStudentRequest
	8,  // 17: user.v1.UserService.UpdateTutorStudent:input_type -> user.v1.UpdateTutorStudentRequest
	9,  // 18: user.v1.UserService.DeleteTutorStudent:input_type -> user.v1.DeleteTutorStudentRequest
	10, // 19: user.v1.UserService.ListTutorStudents:input_type -> user.v1.ListTutorStudentsRequest
	12, // 20: user.v1.UserService.ListTutorsForStudent:input_type -> user.v1.ListTutorsForStudentRequest
	14, // 21: user.v1.UserService.ResolveTutorStudentContext:input_type -> user.v1.ResolveTutorStudentContextRequest
	16, // 22: user.v1.UserService.AcceptInvitationFromTutor:input_type -> user.v1.AcceptInvitationFromTutorRequest
	18, // 23: user.v1.UserService.RegisterViaTelegram:output_type -> user.v1.User
	18, // 24: user.v1.UserService.AuthorizeByAuthHeader:output_type -> user.v1.User
	18, // 25: user.v1.UserService.GetMe:output_type -> user.v1.User
	19, // 26: user.v1.UserService.GetUser:output_type -> user.v1.UserPublic
	18, // 27: user.v1.UserService.UpdateUser:output_type -> user.v1.User
	20, // 28: user.v1.UserService.UpdateTutorProfile:output_type -> user.v1.TutorProfile
	20, // 29: user.v1.UserService.GetTutorProfileByUserId:output_type -> user.v1.TutorProfile
	21, // 30: user.v1.UserService.GetTutorStudent:output_type -> user.v1.TutorStudent
	21, // 31: user.v1.UserService.CreateTutorStudent:output_type -> user.v1.TutorStudent
	21, // 32: user.v1.UserService.UpdateTutorStudent:output_type -> user.v1.TutorStudent
	17, // 33: user.v1.UserService.DeleteTutorStudent:output_type -> user.v1.Empty
	11, // 34: user.v1.UserService.ListTutorStudents:output_type -> user.v1.ListTutorStudentsResponse
	13, // 35: user.v1.UserService.ListTutorsForStudent:output_type -> user.v1.ListTutorsForStudentResponse
	15, // 36: user.v1.UserService.ResolveTutorStudentContext:output_type -> user.v1.ResolvedTutorStudentContext
	17, // 37: user.v1.UserService.AcceptInvitationFromTutor:output_type -> user.v1.Empty
	23, // [23:38] is the sub-list for method output_type
	8,  // [8:23] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_user_service_proto_init() }
func file_user_service_proto_init() {
	if File_user_service_proto != nil {
		return
	}
	file_user_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_user_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_user_service_proto_msgTypes[5].OneofWrappers = []any{}
	file_user_service_proto_msgTypes[7].OneofWrappers = []any{}
	file_user_service_proto_msgTypes[8].OneofWrappers = []any{}
	file_user_service_proto_msgTypes[15].OneofWrappers = []any{}
	file_user_service_proto_msgTypes[18].OneofWrappers = []any{}
	file_user_service_proto_msgTypes[19].OneofWrappers = []any{}
	file_user_service_proto_msgTypes[20].OneofWrappers = []any{}
	file_user_service_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_proto_rawDesc), len(file_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_proto_goTypes,
		DependencyIndexes: file_user_service_proto_depIdxs,
		MessageInfos:      file_user_service_proto_msgTypes,
	}.Build()
	File_user_service_proto = out.File
	file_user_service_proto_goTypes = nil
	file_user_service_proto_depIdxs = nil
}
